name = "xinteria-labs"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "xinteria-labs-production"

[env.staging]
name = "xinteria-labs-staging"

# Uncomment and configure these sections as needed:

# [vars]
# ENVIRONMENT = "production"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "your-database-id"

# [triggers]
# crons = ["0 0 * * *"]

# [build]
# command = "npm run build"
# cwd = "."

# [miniflare]
# kv_persist = true
# d1_persist = true
